// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: customer_service.proto
#ifndef GRPC_customer_5fservice_2eproto__INCLUDED
#define GRPC_customer_5fservice_2eproto__INCLUDED

#include "customer_service.pb.h"

#include <grpc++/support/async_stream.h>
#include <grpc++/impl/rpc_method.h>
#include <grpc++/impl/proto_utils.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/support/async_unary_call.h>
#include <grpc++/support/status.h>
#include <grpc++/support/stub_options.h>
#include <grpc++/support/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace proto {

class CustomerService GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::proto::Person>> ListPerson(::grpc::ClientContext* context, const ::proto::RequestType& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::proto::Person>>(ListPersonRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::proto::Person>> AsyncListPerson(::grpc::ClientContext* context, const ::proto::RequestType& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::proto::Person>>(AsyncListPersonRaw(context, request, cq, tag));
    }
    virtual ::grpc::Status AddPerson(::grpc::ClientContext* context, const ::proto::Person& request, ::proto::ResponseType* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::ResponseType>> AsyncAddPerson(::grpc::ClientContext* context, const ::proto::Person& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::ResponseType>>(AsyncAddPersonRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientReaderInterface< ::proto::Person>* ListPersonRaw(::grpc::ClientContext* context, const ::proto::RequestType& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::proto::Person>* AsyncListPersonRaw(::grpc::ClientContext* context, const ::proto::RequestType& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::proto::ResponseType>* AsyncAddPersonRaw(::grpc::ClientContext* context, const ::proto::Person& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::Channel>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::proto::Person>> ListPerson(::grpc::ClientContext* context, const ::proto::RequestType& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::proto::Person>>(ListPersonRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::proto::Person>> AsyncListPerson(::grpc::ClientContext* context, const ::proto::RequestType& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::proto::Person>>(AsyncListPersonRaw(context, request, cq, tag));
    }
    ::grpc::Status AddPerson(::grpc::ClientContext* context, const ::proto::Person& request, ::proto::ResponseType* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::ResponseType>> AsyncAddPerson(::grpc::ClientContext* context, const ::proto::Person& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::ResponseType>>(AsyncAddPersonRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::Channel> channel_;
    ::grpc::ClientReader< ::proto::Person>* ListPersonRaw(::grpc::ClientContext* context, const ::proto::RequestType& request) GRPC_OVERRIDE;
    ::grpc::ClientAsyncReader< ::proto::Person>* AsyncListPersonRaw(::grpc::ClientContext* context, const ::proto::RequestType& request, ::grpc::CompletionQueue* cq, void* tag) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::proto::ResponseType>* AsyncAddPersonRaw(::grpc::ClientContext* context, const ::proto::Person& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_ListPerson_;
    const ::grpc::RpcMethod rpcmethod_AddPerson_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::Channel>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::SynchronousService {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ListPerson(::grpc::ServerContext* context, const ::proto::RequestType* request, ::grpc::ServerWriter< ::proto::Person>* writer);
    virtual ::grpc::Status AddPerson(::grpc::ServerContext* context, const ::proto::Person* request, ::proto::ResponseType* response);
    ::grpc::RpcService* service() GRPC_OVERRIDE GRPC_FINAL;
   private:
    std::unique_ptr< ::grpc::RpcService> service_;
  };
  class AsyncService GRPC_FINAL : public ::grpc::AsynchronousService {
   public:
    explicit AsyncService();
    ~AsyncService() {};
    void RequestListPerson(::grpc::ServerContext* context, ::proto::RequestType* request, ::grpc::ServerAsyncWriter< ::proto::Person>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
    void RequestAddPerson(::grpc::ServerContext* context, ::proto::Person* request, ::grpc::ServerAsyncResponseWriter< ::proto::ResponseType>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
  };
};

}  // namespace proto


#endif  // GRPC_customer_5fservice_2eproto__INCLUDED
